### ISSUE TITLE
research paprer not available

### ISSUE THREAD

**Issue by arkinrc** [yasinalm/gramme#5]
Hi,
i tried to download this research paper mentioned in this repo but it's not availabe. could you please share this paper. 
secondly, results for radiate dataset only with stereo are good but others such as mono and lidar+camera results are bad. i tried to test using your provided trained model but results are still not good showing arbitrary and distorted trajectories. 

Stereo only:

![pred_nogt](https://user-images.githubusercontent.com/42382784/175846733-2a1778cf-a2d5-4dd8-909d-eaa6456c53f8.png)

lidar + camera for radiate dataset pretrained model results:

1. mono2radarpred_notgt

![mono2radarpred_nogt](https://user-images.githubusercontent.com/42382784/175846545-0ab09dab-8cce-403b-9358-89a22427b2d8.png)

 2. monopred_nogt:
 
![monopred_nogt](https://user-images.githubusercontent.com/42382784/175846633-968a80a6-16d7-4c73-8cd2-961ff924b8e1.png)

3. radarpred_nogt:

![radarpred_nogt](https://user-images.githubusercontent.com/42382784/175846648-91f4dd05-a2e8-496d-b43e-22e31df132cb.png)

looking forward to your feedback.

Thanks

**Comment by yasinalm** [comment]
Thank you for your interest in our work. The paper is available in the link below. Please let us know if you have any further questions after reading the full article.

https://www.nature.com/articles/s42256-022-00520-5

**Comment by QingTianNNN** [comment]
I think you're cheating us!!! No matter how I conduct my experiments, I find that I can't achieve your results. I couldn't even achieve the results in the article using your pre-trained model
